---
fail_fast: false
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix, "lf"]
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master, --branch, devel]
      - id: trailing-whitespace
        exclude: |
          (?x)(
              \.diff$|
              \.patch$
          )
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.35.1"
    hooks:
      - id: yamllint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        exclude: test/utilities/shunit2/
  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: "v1.7.1.15"
    hooks:
      - id: actionlint
